//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class animal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public animal()
        {
            this.adopcion = new HashSet<adopcion>();
            this.seguimiento = new HashSet<seguimiento>();
        }
    
        public int idAnimal { get; set; }
        public string nombre { get; set; }
        public string sexo { get; set; }
        public string raza { get; set; }
        public bool castrado { get; set; }
        public string edad { get; set; }
        public System.DateTime fechaIngreso { get; set; }
        public int idGSanguineo { get; set; }
        public int idOrganizacion { get; set; }
        public bool habilitado { get; set; }
        public string especie { get; set; }
        public bool adoptado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<adopcion> adopcion { get; set; }
        public virtual grupoSanguineo grupoSanguineo { get; set; }
        public virtual organizacion organizacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<seguimiento> seguimiento { get; set; }
    }
}
