//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class organizacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public organizacion()
        {
            this.animal = new HashSet<animal>();
            this.orgProveedor = new HashSet<orgProveedor>();
            this.usuario = new HashSet<usuario>();
        }
    
        public int idOrganizacion { get; set; }
        public string tipo { get; set; }
        public string nombre { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> habilitado { get; set; }
        public Nullable<int> idProvincia { get; set; }
        public Nullable<int> idCanton { get; set; }
        public Nullable<int> idDistrito { get; set; }
        public string detalleDireccion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<animal> animal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orgProveedor> orgProveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuario> usuario { get; set; }
        public virtual canton canton { get; set; }
        public virtual distrito distrito { get; set; }
        public virtual provincia provincia { get; set; }
    }
}
